version: "3.8"

services:
  camunda:
    image: camunda/zeebe:8.4.1
    ports:
      - "26500:26500"
      - "9600:9600"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    depends_on:
      - ollama
      - redis
